
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Form Workout Log      <small><?= cclang('detail', ['Form Workout Log']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/form_workout_log'); ?>">Form Workout Log</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body "></div>

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Form Workout Log</h3>
                     <h5 class="widget-user-desc">Detail Form Workout Log</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_form_workout_log" id="form_form_workout_log" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Workout Id </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->workout_id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Patient Id </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->patient_id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Average Accuracy </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->average_accuracy); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Average Time </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->average_time); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Average Pain Score </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->average_pain_score); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pain Face </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->pain_face); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pain Motion </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->pain_motion); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pain Scream </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->pain_scream); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pain Restless </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workout_log->pain_restless); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('form_workout_log_update', function() use ($form_workout_log){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit form_workout_log (Ctrl+e)" href="<?= site_url('administrator/form_workout_log/edit/'.$form_workout_log->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Form Workout Log']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/form_workout_log/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Form Workout Log']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>