
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Form Workoutstep      <small><?= cclang('detail', ['Form Workoutstep']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/form_workoutstep'); ?>">Form Workoutstep</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Form Workoutstep</h3>
                     <h5 class="widget-user-desc">Detail Form Workoutstep</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_form_workoutstep" id="form_form_workoutstep" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Workout Id </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->workout_id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Step Id </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->step_id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nose X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->nose_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Eye X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_eye_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Eye X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_eye_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Ear X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_ear_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Ear X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_ear_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Shoulder X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_shoulder_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Shoulder X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_shoulder_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Elbow X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_elbow_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Elbow X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_elbow_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Wrist X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_wrist_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Wrist X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_wrist_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Hip X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_hip_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Hip X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_hip_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Knee X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_knee_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Knee X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_knee_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Ankle X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_ankle_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Ankle X </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_ankle_x); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nose Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->nose_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Eye Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_eye_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Eye Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_eye_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Ear Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_ear_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Ear Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_ear_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Shoulder Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_shoulder_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Shoulder Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_shoulder_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Elbow Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_elbow_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Elbow Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_elbow_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Wrist Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_wrist_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Wrist Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_wrist_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Hip Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_hip_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Hip Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_hip_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Knee Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_knee_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Knee Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_knee_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Right Ankle Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->right_ankle_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Left Ankle Y </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->left_ankle_y); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nose Check </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->nose_check); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Eye Check </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->eye_check); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ear Check </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->ear_check); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shoulder Check </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->shoulder_check); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Elbow Check </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->elbow_check); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Wrist Check </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->wrist_check); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Hip Check </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->hip_check); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Knee Check </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->knee_check); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Foot Check </label>

                        <div class="col-sm-8">
                           <?= _ent($form_workoutstep->foot_check); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('form_workoutstep_update', function() use ($form_workoutstep){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit form_workoutstep (Ctrl+e)" href="<?= site_url('administrator/form_workoutstep/edit/'.$form_workoutstep->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Form Workoutstep']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/form_workoutstep/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Form Workoutstep']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>