
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Form_user/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('form_user') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('form_user') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('form_user_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('form_user')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/form_user/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('form_user')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('form_user_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('form_user') ?> " href="<?= site_url('administrator/form_user/export?q='.$this->input->get('q').'&f='.$this->input->get('f')); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('form_user_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('form_user') ?> " href="<?= site_url('administrator/form_user/export_pdf?q='.$this->input->get('q').'&f='.$this->input->get('f')); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('form_user') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('form_user')]); ?>  <i class="label bg-yellow"><?= $form_user_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_form_user" id="form_form_user" action="<?= base_url('administrator/form_user/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th data-field="role"data-sort="1" data-primary-key="0"> <?= cclang('role') ?></th>
                           <th data-field="username"data-sort="1" data-primary-key="0"> <?= cclang('username') ?></th>
                           <th data-field="password"data-sort="1" data-primary-key="0"> <?= cclang('password') ?></th>
                           <th data-field="first_name"data-sort="1" data-primary-key="0"> <?= cclang('first_name') ?></th>
                           <th data-field="last_name"data-sort="1" data-primary-key="0"> <?= cclang('last_name') ?></th>
                           <th data-field="gender"data-sort="1" data-primary-key="0"> <?= cclang('gender') ?></th>
                           <th data-field="age"data-sort="1" data-primary-key="0"> <?= cclang('age') ?></th>
                           <th data-field="height"data-sort="1" data-primary-key="0"> <?= cclang('height') ?></th>
                           <th data-field="weight"data-sort="1" data-primary-key="0"> <?= cclang('weight') ?></th>
                           <th data-field="bmi"data-sort="1" data-primary-key="0"> <?= cclang('bmi') ?></th>
                           <th data-field="position"data-sort="1" data-primary-key="0"> <?= cclang('position') ?></th>
                           <th data-field="institution"data-sort="1" data-primary-key="0"> <?= cclang('institution') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_form_user">
                     <?php foreach($form_users as $form_user): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $form_user->id; ?>">
                           </td>
                                                       
                           <td><?= _ent($form_user->role); ?></td> 
                           <td><?= _ent($form_user->username); ?></td> 
                           <td><?= _ent($form_user->password); ?></td> 
                           <td><?= _ent($form_user->first_name); ?></td> 
                           <td><?= _ent($form_user->last_name); ?></td> 
                           <td><?= _ent($form_user->gender); ?></td> 
                           <td><?= _ent($form_user->age); ?></td> 
                           <td><?= _ent($form_user->height); ?></td> 
                           <td><?= _ent($form_user->weight); ?></td> 
                           <td><?= _ent($form_user->bmi); ?></td> 
                           <td><?= _ent($form_user->position); ?></td> 
                           <td><?= _ent($form_user->institution); ?></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('form_user_view', function() use ($form_user){?>
                                 <a href="<?= site_url('administrator/form_user/single_pdf/' .$form_user->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?>
                              <a href="<?= site_url('administrator/form_user/view/' . $form_user->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('form_user_update', function() use ($form_user){?>
                              <a href="<?= site_url('administrator/form_user/edit/' . $form_user->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('form_user_delete', function() use ($form_user){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/form_user/delete/' . $form_user->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($form_user_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Form User data is not available
                           </td>
                         </tr>
                      <?php endif; ?>

                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'role' ? 'selected' :''; ?> value="role">Role</option>
                           <option <?= $this->input->get('f') == 'username' ? 'selected' :''; ?> value="username">Username</option>
                           <option <?= $this->input->get('f') == 'password' ? 'selected' :''; ?> value="password">Password</option>
                           <option <?= $this->input->get('f') == 'first_name' ? 'selected' :''; ?> value="first_name">First Name</option>
                           <option <?= $this->input->get('f') == 'last_name' ? 'selected' :''; ?> value="last_name">Last Name</option>
                           <option <?= $this->input->get('f') == 'gender' ? 'selected' :''; ?> value="gender">Gender</option>
                           <option <?= $this->input->get('f') == 'age' ? 'selected' :''; ?> value="age">Age</option>
                           <option <?= $this->input->get('f') == 'height' ? 'selected' :''; ?> value="height">Height</option>
                           <option <?= $this->input->get('f') == 'weight' ? 'selected' :''; ?> value="weight">Weight</option>
                           <option <?= $this->input->get('f') == 'bmi' ? 'selected' :''; ?> value="bmi">Bmi</option>
                           <option <?= $this->input->get('f') == 'position' ? 'selected' :''; ?> value="position">Position</option>
                           <option <?= $this->input->get('f') == 'institution' ? 'selected' :''; ?> value="institution">Institution</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/form_user');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_form_user').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/form_user/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('form_user', $('table.dataTable'));
  }); /*end doc ready*/
</script>