<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
   //This page is a result of an autogenerated content made by running test.html with firefox.
   function domo() {

      // Binding keys
      $('*').bind('keydown', 'Ctrl+a', function assets() {
         window.location.href = BASE_URL + '/administrator/Form_workout/add';
         return false;
      });

      $('*').bind('keydown', 'Ctrl+f', function assets() {
         $('#sbtn').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+x', function assets() {
         $('#reset').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+b', function assets() {

         $('#reset').trigger('click');
         return false;
      });
   }

   jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<!-- <section class="content-header">
   <h1>
      <?= cclang('form_workout') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('form_workout') ?></li>
   </ol>
</section> -->
<!-- Main content -->
<section class="content">
   <div class="row">

      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">

                        <a class="btn btn-flat btn-success btn_action" id="btn_cancel" title="กรุณาเพิ่มท่าผ่านทางแอปพลิเคชัน ViHab บนสมาร์ทโฟน">
                           <i class="fa fa-plus-square-o"></i> เพิ่มท่ากายภาพ
                        </a>
                        <!-- <?php is_allowed('form_workout_export', function () { ?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('form_workout') ?> " href="<?= site_url('administrator/form_workout/export?q=' . $this->input->get('q') . '&f=' . $this->input->get('f')); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('form_workout_export', function () { ?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('form_workout') ?> " href="<?= site_url('administrator/form_workout/export_pdf?q=' . $this->input->get('q') . '&f=' . $this->input->get('f')); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?> -->
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">
                        ท่ากายภาพบำบัด
                        <small><i class="label bg-yellow"><?= $form_workout_counts; ?> ท่า</i></small>
                     </h3>
                     <h5>&nbsp;&nbsp;&nbsp;&nbsp;รายการแสดงท่ากายภาพบำบัดทั้งหมด</h5>
                  </div>

                  <form name="form_form_workout" id="form_form_workout" action="<?= base_url('administrator/form_workout/index'); ?>">

                     <div class="table-responsive">
                        <table class="table table-bordered table-striped dataTable">
                           <thead>
                              <tr class="">
                                 <th>
                                    <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                                 </th>
                                 <!-- <th data-field="trainer_id" data-sort="1" data-primary-key="0">ผู้บันทึกท่า</th> -->
                                 <th data-field="name" data-sort="1" data-primary-key="0">ชื่อท่ากายภาพ</th>
                                 <th data-field="description" data-sort="1" data-primary-key="0">รายละเอียด</th>
                                 <th data-field="method" data-sort="1" data-primary-key="0">วิธีการ</th>
                                 <th data-field="total_step" data-sort="1" data-primary-key="0">ขั้นตอนต่อท่า(ครั้ง)</th>
                                 <th data-field="total_second" data-sort="1" data-primary-key="0">เวลาต่อขั้นตอน(วินาที)</th>
                                 <th data-field="total_count" data-sort="1" data-primary-key="0">จำนวนครั้งต่อชุด</th>
                                 <th data-field="created_at" data-sort="1" data-primary-key="0">วันที่บันทึก</th>
                                 <th></th>
                              </tr> 
                           </thead>
                           <tbody id="tbody_form_workout">
                              <?php foreach ($form_workouts as $form_workout) : ?>
                                 <tr>
                                    <td width="5">
                                       <input type="checkbox" class="flat-red check" name="id[]" value="<?= $form_workout->id; ?>">
                                    </td>

                                    <!-- <td><?= _ent($form_workout->trainer_id); ?></td> -->
                                    <td><?= _ent($form_workout->name); ?></td>
                                    <td><?= _ent($form_workout->description); ?></td>
                                    <td><?= _ent($form_workout->method); ?></td>
                                    <td><?= _ent($form_workout->total_step); ?></td>
                                    <td><?= _ent($form_workout->total_second); ?></td>
                                    <td><?= _ent($form_workout->total_count); ?></td>
                                    <td><?= _ent($form_workout->created_at); ?></td>
                                    <td width="200">

                                       <?php is_allowed('form_workout_view', function () use ($form_workout) { ?>
                                          <!-- <a href="<?= site_url('administrator/form_workout/single_pdf/' . $form_workout->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?> -->
                                             <!-- <a href="<?= site_url('administrator/form_workout/view/' . $form_workout->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?> -->
                                             <?php }) ?>
                                             <?php is_allowed('form_workout_update', function () use ($form_workout) { ?>
                                                <a href="<?= site_url('administrator/form_workout/edit/' . $form_workout->id); ?>" class="label-default"><i class="fa fa-edit "></i> แก้ไข</a>
                                             <?php }) ?>
                                             <?php is_allowed('form_workout_delete', function () use ($form_workout) { ?>
                                                <a href="javascript:void(0);" data-href="<?= site_url('administrator/form_workout/delete/' . $form_workout->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> ลบ</a>
                                             <?php }) ?>

                                    </td>
                                 </tr>
                              <?php endforeach; ?>
                              <?php if ($form_workout_counts == 0) : ?>
                                 <tr>
                                    <td colspan="100">
                                       Form Workout data is not available
                                    </td>
                                 </tr>
                              <?php endif; ?>

                           </tbody>
                        </table>
                     </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 ">
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email">
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  ">
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 ">
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field">
                           <option value=""><?= cclang('all'); ?></option>
                           <option <?= $this->input->get('f') == 'trainer_id' ? 'selected' : ''; ?> value="trainer_id">Trainer Id</option>
                           <option <?= $this->input->get('f') == 'name' ? 'selected' : ''; ?> value="name">Name</option>
                           <option <?= $this->input->get('f') == 'description' ? 'selected' : ''; ?> value="description">Description</option>
                           <option <?= $this->input->get('f') == 'method' ? 'selected' : ''; ?> value="method">Method</option>
                           <option <?= $this->input->get('f') == 'total_step' ? 'selected' : ''; ?> value="total_step">Total Step</option>
                           <option <?= $this->input->get('f') == 'total_second' ? 'selected' : ''; ?> value="total_second">Total Second</option>
                           <option <?= $this->input->get('f') == 'tracking_point' ? 'selected' : ''; ?> value="tracking_point">Tracking Point</option>
                           <option <?= $this->input->get('f') == 'created_at' ? 'selected' : ''; ?> value="created_at">Created At</option>
                           <option <?= $this->input->get('f') == 'total_count' ? 'selected' : ''; ?> value="total_count">Total Count</option>
                        </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                           Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/form_workout'); ?>" title="<?= cclang('reset_filter'); ?>">
                           <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate">
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
   $(document).ready(function() {

      $('#btn_cancel').click(function() {
         swal({
               title: "ดาวน์โหลด ViHab",
               text: "กรุณาเพิ่มท่ากายภาพบำบัดด้วยแอปพลิเคชัน ViHab บนสมาร์ทโฟนระบบปฏิบัติการแอนดรอยด์",
               // type: "warning",
               // showCancelButton: true,
               confirmButtonColor: "#00CCFF",
               confirmButtonText: "ยืนยัน",
               // cancelButtonText: "No!",
               closeOnConfirm: true,
               closeOnCancel: true,
               imageUrl: 'https://vihab.om4you.com/download/frame-4.png',

            },
            function(isConfirm) {
               if (isConfirm) {
                  window.location.href = BASE_URL + 'administrator/form_workout';
               }
            });

         return false;
      }); /*end btn cancel*/



      $('.remove-data').click(function() {

         var url = $(this).attr('data-href');

         swal({
               title: "<?= cclang('are_you_sure'); ?>",
               text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
               type: "warning",
               showCancelButton: true,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
               cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
               closeOnConfirm: true,
               closeOnCancel: true
            },
            function(isConfirm) {
               if (isConfirm) {
                  document.location.href = url;
               }
            });

         return false;
      });


      $('#apply').click(function() {

         var bulk = $('#bulk');
         var serialize_bulk = $('#form_form_workout').serialize();

         if (bulk.val() == 'delete') {
            swal({
                  title: "<?= cclang('are_you_sure'); ?>",
                  text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
                  type: "warning",
                  showCancelButton: true,
                  confirmButtonColor: "#DD6B55",
                  confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
                  cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
                  closeOnConfirm: true,
                  closeOnCancel: true
               },
               function(isConfirm) {
                  if (isConfirm) {
                     document.location.href = BASE_URL + '/administrator/form_workout/delete?' + serialize_bulk;
                  }
               });

            return false;

         } else if (bulk.val() == '') {
            swal({
               title: "Upss",
               text: "<?= cclang('please_choose_bulk_action_first'); ?>",
               type: "warning",
               showCancelButton: false,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "Okay!",
               closeOnConfirm: true,
               closeOnCancel: true
            });

            return false;
         }

         return false;

      }); /*end appliy click*/


      //check all
      var checkAll = $('#check_all');
      var checkboxes = $('input.check');

      checkAll.on('ifChecked ifUnchecked', function(event) {
         if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
         } else {
            checkboxes.iCheck('uncheck');
         }
      });

      checkboxes.on('ifChanged', function(event) {
         if (checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
         } else {
            checkAll.removeProp('checked');
         }
         checkAll.iCheck('update');
      });
      initSortable('form_workout', $('table.dataTable'));
   }); /*end doc ready*/
</script>